#!/bin/bash
echo "BATTERY"
cat /sys/class/power_supply/BAT1/capacity
echo ""
echo "RAM"
free -h | grep Mem | awk '{ print $3 }'
echo ""
echo "VOLUME"
pamixer --get-volume
echo ""
echo "TIME"
date +"%H:%M"
echo ""
echo "DATE"
date +"%d/%m/%Y"
echo ""
